
adminer:
    path: /adminer
    controller: App\Controller\AdminerController::index

# Routes for HomeController
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]


# Routes for ConsoleController
app_console_index:
    path: /console
    controller: App\Controller\ConsoleController::index
    methods: [GET]

app_console_new:
    path: /console/new
    controller: App\Controller\ConsoleController::new
    methods: [GET, POST]

app_console_edit:
    path: /console/{id}/edit
    controller: App\Controller\ConsoleController::edit
    methods: [GET, POST]

app_console_show:
    path: /console/{id}
    controller: App\Controller\ConsoleController::show
    methods: [GET]

app_console_delete:
    path: /console/{id}
    controller: App\Controller\ConsoleController::delete
    methods: [DELETE]

# Routes for JeuxVideosController
app_jeux_videos_index:
    path: /jeuxvideos
    controller: App\Controller\JeuxVideosController::index
    methods: [GET]

app_jeux_videos_new:
    path: /jeuxvideos/new
    controller: App\Controller\JeuxVideosController::new
    methods: [GET, POST]

app_jeux_videos_edit:
    path: /jeuxvideos/{id}/edit
    controller: App\Controller\JeuxVideosController::edit
    methods: [GET, POST]

app_jeux_videos_show:
    path: /jeuxvideos/{id}
    controller: App\Controller\JeuxVideosController::show
    methods: [GET]

app_jeux_videos_delete:
    path: /jeuxvideos/{id}
    controller: App\Controller\JeuxVideosController::delete
    methods: [DELETE]
